services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./.env.docker
    volumes:
      # Sincroniza tu código con el contenedor
      - .:/app
      # --- CORRECCIÓN CLAVE ---
      # Evita que tu carpeta node_modules local sobreescriba la del contenedor
      - /app/node_modules
    depends_on:
      - postgres

volumes:
  postgres_data: